In [7]:
import numpy as np
my_list = [ 10 , 20 , 30 , 40 , 50 ]
a = np.array (my_list)
print(my_list)
print(a)

[10, 20, 30, 40, 50]
[10 20 30 40 50]


In [11]:
import numpy as np
my_list = [ 1 , 2 , 3 , 4 , 5 ]
b = np.array(my_list)
print(b)

[1 2 3 4 5]


In [31]:
a = np.array ([ 10 , 20 , 30 , 40 , 50 ])
b = np.array([ 1 , 2 , 3 , 4 , 5 ])
dot_product = sum( a * b )
reshape_array = a.reshape( 5 , 1 )
print ( a + b )
print ( a - b )
print ( a * b )
print ( a / b )
print ( a.min())
print ( a.max())
print (dot_product)
print(reshape_array)


[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
10
50
550
[[10]
 [20]
 [30]
 [40]
 [50]]


In [11]:
import pandas as pd 
student_data = [ [ 'Alice' ,  20 ,  'A'  , 85 ] ,
                 [ 'Bob' ,  22 ,  'B' ,  78  ] ,
                 [ 'Charlie' , 19 , 'A' , 92 ] ,
                 [ 'David' , 21 , 'C' , 65 ] ,
                 [ 'Eva' ,  20 , 'B' ,  74 ] ]

df = pd.DataFrame(student_data, columns=['Name' , 'Age' , 'Grade' , 'Marks'])
df


Name  Age Grade  Marks
0    Alice   20     A     85
1      Bob   22     B     78
2  Charlie   19     A     92
3    David   21     C     65
4      Eva   20     B     74

In [13]:
import pandas as pd 
student_data = [ [ 'Alice' ,  20 ,  'A'  , 85 ] ,
                 [ 'Bob' ,  22 ,  'B' ,  78  ] ,
                 [ 'Charlie' , 19 , 'A' , 92 ] ,
                 [ 'David' , 21 , 'C' , 65 ] ,
                 [ 'Eva' ,  20 , 'B' ,  74 ] ]

df = pd.DataFrame(student_data, columns=['Name' , 'Age' , 'Grade' , 'Marks'])
df
df.iloc [0:3]

Name  Age Grade  Marks
0    Alice   20     A     85
1      Bob   22     B     78
2  Charlie   19     A     92

In [17]:
import pandas as pd 
student_data = [ [ 'Alice' ,  20 ,  'A'  , 85 ] ,
                 [ 'Bob' ,  22 ,  'B' ,  78  ] ,
                 [ 'Charlie' , 19 , 'A' , 92 ] ,
                 [ 'David' , 21 , 'C' , 65 ] ,
                 [ 'Eva' ,  20 , 'B' ,  74 ] ]

df = pd.DataFrame(student_data, columns=['Name' , 'Age' , 'Grade' , 'Marks'])
df
df.iloc [0:3]
df [['Name' , 'Marks']]


Name  Marks
0    Alice     85
1      Bob     78
2  Charlie     92
3    David     65
4      Eva     74

In [23]:
import pandas as pd 
student_data = [ [ 'Alice' ,  20 ,  'A'  , 85 ] ,
                 [ 'Bob' ,  22 ,  'B' ,  78  ] ,
                 [ 'Charlie' , 19 , 'A' , 92 ] ,
                 [ 'David' , 21 , 'C' , 65 ] ,
                 [ 'Eva' ,  20 , 'B' ,  74 ] ]

df = pd.DataFrame(student_data, columns=['Name' , 'Age' , 'Grade' , 'Marks'])
df
df.iloc [0:3]
df [['Name' , 'Marks']]
Grade = df[(df['Grade']=='A')]
Grade

Name  Age Grade  Marks
0    Alice   20     A     85
2  Charlie   19     A     92